name: Build & Deploy

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          repo: foad/foad.github.io
          target_branch: master
          keep_history: true
          build_dir: build
          committer: Dan Foad <dan@foad.dev>
          author: Dan Foad <dan@foad.dev>
          fqdn: https://foad.dev
          verbose: true
        env:
          GH_PAT: ${{ secrets.PAT }}
